import 'server-only';

import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { eq } from 'drizzle-orm';
import { db } from '@/db';
import { media } from '@/db/schema';

export const MAX_UPLOAD_BYTES = 5 * 1024 * 1024;

const EXTENSIONS: Record<string, string> = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/webp': 'webp',
  'image/gif': 'gif',
  'image/avif': 'avif',
};

/**
 * Trusts the file's magic bytes rather than the declared Content-Type, so a
 * script renamed to .png never reaches disk.
 */
function sniff(bytes: Uint8Array): string | null {
  const startsWith = (...sig: number[]) => sig.every((b, i) => bytes[i] === b);
  const ascii = (offset: number, text: string) =>
    [...text].every((c, i) => bytes[offset + i] === c.charCodeAt(0));

  if (startsWith(0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a)) return 'image/png';
  if (startsWith(0xff, 0xd8, 0xff)) return 'image/jpeg';
  if (startsWith(0x47, 0x49, 0x46, 0x38)) return 'image/gif';
  if (ascii(0, 'RIFF') && ascii(8, 'WEBP')) return 'image/webp';
  if (ascii(4, 'ftyp') && (ascii(8, 'avif') || ascii(8, 'avis'))) return 'image/avif';
  return null;
}

/**
 * Uploads live in a fixed subfolder of the working directory. Keeping the base
 * statically resolvable stops the bundler from tracing the whole project into
 * the server output. A real deployment would swap this module for object
 * storage; only `storeImage` and `loadImage` would need to change.
 */
const UPLOAD_DIR = join(process.cwd(), 'uploads');

/** Exactly the shape storeImage writes: a uuid plus a known extension. */
const STORED_FILENAME = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(png|jpg|webp|gif|avif)$/i;

export type StoredMedia = { id: string; url: string };

export async function storeImage(file: File, ownerId: string): Promise<StoredMedia | { error: string }> {
  if (file.size === 0) return { error: 'ეს ფაილი ცარიელია.' };
  if (file.size > MAX_UPLOAD_BYTES) return { error: 'სურათი 5 მბ-ზე მეტი არ უნდა იყოს.' };

  const bytes = new Uint8Array(await file.arrayBuffer());
  const mimeType = sniff(bytes);
  if (!mimeType) return { error: 'ეს არ ჰგავს PNG, JPEG, WebP, GIF ან AVIF სურათს.' };

  const id = randomUUID();
  const filename = `${id}.${EXTENSIONS[mimeType]}`;

  await mkdir(UPLOAD_DIR, { recursive: true });
  await writeFile(join(UPLOAD_DIR, filename), bytes);

  await db.insert(media).values({
    id,
    ownerId,
    mimeType,
    byteSize: bytes.byteLength,
    storagePath: filename,
  });

  return { id, url: `/api/media/${id}` };
}

export async function loadImage(id: string) {
  const [row] = await db.select().from(media).where(eq(media.id, id)).limit(1);
  if (!row) return null;

  // storagePath is generated by us, never user input, but check the shape anyway
  // so a bad row can never walk outside the upload directory.
  if (!STORED_FILENAME.test(row.storagePath)) return null;

  try {
    return { bytes: await readFile(join(UPLOAD_DIR, row.storagePath)), mimeType: row.mimeType };
  } catch {
    return null;
  }
}

/**
 * Removes every image a user uploaded, files first. Called before the account
 * row goes: the media rows would otherwise survive it with a null owner.
 */
export async function deleteImagesOwnedBy(ownerId: string) {
  const rows = await db
    .delete(media)
    .where(eq(media.ownerId, ownerId))
    .returning({ storagePath: media.storagePath });

  // Settled, not all: a file that will not go must not block the account
  // deletion that called this. Its row is already gone, so nothing serves it.
  const results = await Promise.allSettled(
    rows
      .filter((row) => STORED_FILENAME.test(row.storagePath))
      .map((row) => rm(join(UPLOAD_DIR, row.storagePath), { force: true })),
  );
  for (const result of results) {
    if (result.status === 'rejected') console.error('[storage] could not delete upload', result.reason);
  }
}
